import type { RankingMetricId, SunburstNode } from "./types";
import { metricValue } from "./types";

/**
 * Category → CSS custom property.
 *
 * The payload's own `category_colors` remain the source of truth for the data
 * pipeline (scripts/build_analytics_payloads.py also feeds the Streamlit app
 * and is regenerated by an automated job, so it is not edited here). These
 * tokens re-derive those hues to clear contrast on both the light and dark
 * grounds; anything unrecognised falls back to the payload value.
 */
export function categoryToken(name: string): string {
  const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, "-");
  return `--viz-cat-${slug}`;
}

export function categoryColor(
  name: string,
  fallback: Record<string, string>,
): string {
  const token = categoryToken(name);
  const payloadColor = fallback[name];
  return payloadColor
    ? `var(${token}, ${payloadColor})`
    : `var(${token}, var(--viz-null))`;
}

/** Indices into the 7-stop ramp used for the 5 discrete bins. */
const BIN_STOPS = [0, 2, 3, 5, 6];

export type Bins = {
  /** Upper bound of each bin, over the non-zero values only. */
  thresholds: number[];
  /** How many bins are in use (3 for sparse metrics, else 5). */
  count: number;
  /** Leaves with no value / zero for this metric. */
  zeros: number;
  /** Leaves with a usable value. */
  covered: number;
  min: number;
  max: number;
};

/**
 * Quantile bins over the non-zero values.
 *
 * A continuous log1p scale over the full set — what the Streamlit reference
 * does at tabs/ecosystem_tab.py:198 — collapses for the sparse metrics:
 * citations is zero for 2,370 of 2,691 projects and downloads for 1,824, so
 * almost the whole ring lands on one colour. Binning over the covered subset
 * and giving "no value" its own detached swatch keeps the ring readable and
 * makes the sparsity visible instead of hiding it.
 */
export function computeBins(values: (number | null)[]): Bins {
  const nonZero: number[] = [];
  let zeros = 0;
  for (const value of values) {
    if (value === null || value <= 0) zeros += 1;
    else nonZero.push(value);
  }
  nonZero.sort((a, b) => a - b);

  const covered = nonZero.length;
  if (covered === 0) {
    return { thresholds: [], count: 0, zeros, covered: 0, min: 0, max: 0 };
  }

  const count = covered < 20 ? 3 : 5;
  const thresholds: number[] = [];
  for (let i = 1; i < count; i += 1) {
    const position = (i / count) * (covered - 1);
    thresholds.push(nonZero[Math.round(position)]);
  }
  return {
    thresholds,
    count,
    zeros,
    covered,
    min: nonZero[0],
    max: nonZero[covered - 1],
  };
}

/** Bin index for a value, or -1 for "no data". */
export function binOf(value: number | null, bins: Bins): number {
  if (value === null || value <= 0 || bins.count === 0) return -1;
  let index = 0;
  while (index < bins.thresholds.length && value > bins.thresholds[index]) {
    index += 1;
  }
  return index;
}

/**
 * How saturated a project arc is, as a share of its category hue.
 *
 * The metric is encoded as depth *within* the category colour rather than on a
 * separate ramp, so a category's wedge stays one family from the centre to the
 * rim. Mixing toward --viz-arc-stroke (the panel ground) means the same
 * percentages read correctly in both themes: they wash out on light, and darken
 * on dark.
 */
// Floor for the lightest bin. Below about 0.45 the low-score arcs wash out to
// near-background and the ring stops reading as data.
const MIN_SHARE = 0.45;

export function binShare(index: number, count: number): number {
  if (count <= 1) return 1;
  return MIN_SHARE + (index / (count - 1)) * (1 - MIN_SHARE);
}

/** Project fill: the category hue, stepped by the metric bin. */
export function binFillInHue(
  hue: string,
  index: number,
  count: number,
): string {
  if (index < 0) return "var(--viz-null)";
  const share = Math.round(binShare(index, count) * 100);
  return share >= 100
    ? hue
    : `color-mix(in srgb, ${hue} ${share}%, var(--viz-arc-stroke))`;
}

export function binFillsInHue(hue: string, count: number): string[] {
  return Array.from({ length: count }, (_, index) =>
    binFillInHue(hue, index, count),
  );
}

/** Neutral ramp, for surfaces that are not inside one category's wedge. */
export function binFill(index: number, count: number): string {
  if (index < 0) return "var(--viz-null)";
  const stop =
    count === 5
      ? BIN_STOPS[index]
      : BIN_STOPS[Math.round((index / Math.max(count - 1, 1)) * 4)];
  return `var(--viz-seq-${stop})`;
}

export function binFills(count: number): string[] {
  return Array.from({ length: count }, (_, index) => binFill(index, count));
}

/** Fill for any node: branches take the category hue, leaves the metric bin. */
export function fillFor(
  node: SunburstNode,
  ring: number,
  metric: RankingMetricId,
  bins: Bins,
  categoryColors: Record<string, string>,
): string {
  const base = categoryColor(node.category, categoryColors);

  // Branches — category and sub-category — share the full category hue, as the
  // Plotly reference does; the stroke gap is what separates the rings. Tinting
  // the sub-category ring toward the panel ground lightened it in the light
  // theme but DARKENED it in the dark one, dropping its fixed-ink labels to
  // 2.90:1 at worst. At full hue the same labels clear 4.65:1.
  if (node.kind !== "project") return base;

  return binFillInHue(base, binOf(metricValue(node, metric), bins), bins.count);
}
